# Generated by Django 3.2.6 on 2021-10-18 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20211007_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 46, 1, 777927, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
